Optimized Selection of Miners for Queries - Carlo Casorzo
namoray/nineteen pull request #71
Opened 2024-10-18 18:57 UTC by deepbludev

## Overview

This solution enhances the selection process of miners for both organic and synthetic queries. The goal is to ensure high-quality responses for users while providing promoting exploration for new miners.

## Key Improvements

1. **Differentiated Selection Criteria**

   - **Organic Queries**: Prioritize miners with higher performance scores (`PERIOD_SCORE`) to ensure users receive top-quality responses.
   - **Synthetic Queries**: Prioritize miners with fewer total requests made (`TOTAL_REQUESTS_MADE`) to assess and evaluate less-experienced or new miners.

2. **Two-Step Contender Selection Process**

   For both organic and synthetic queries, a two-step process is implemented:

   - **Initial Query**: Select miners based on the primary criterion for the query type.
     - *Organic Queries*: Highest `PERIOD_SCORE`.
     - *Synthetic Queries*: Least `TOTAL_REQUESTS_MADE`.
   - **Secondary Query**: If the initial query doesn't yield enough miners (`top_x`), fill the remaining slots by selecting miners with the least `TOTAL_REQUESTS_MADE`. This ensures the inclusion of newer miners.

3. **Promoting New Miners**

   - By prioritizing miners with fewer total requests in the secondary query for both query types, the system ensures new miners are given opportunities to participate, allowing them to build performance history and improve their scores.

4. **Weighted Scoring Based on Query Type**

   - Assign higher weights to performance data from organic queries in scoring calculations. This emphasizes the importance of real user interactions in evaluating miner performance over synthetic assessments.

5. **Efficient Database Operations**

   - Utilize indexed columns (`PERIOD_SCORE` and `TOTAL_REQUESTS_MADE`) in queries to optimize database performance and ensure quick retrieval of contenders.

## Detailed Selection Process

### Initial Query

- **Organic Queries**

  - **Objective**: Deliver responses from the best-performing miners to users.
  - **Selection Criterion**: Miners are ranked and selected based on the highest `PERIOD_SCORE`.

- **Synthetic Queries**

  - **Objective**: Assess and evaluate miners who have had fewer opportunities.
  - **Selection Criterion**: Miners are ranked and selected based on the least `TOTAL_REQUESTS_MADE`.

### Secondary Query

- **Purpose**: Ensure the required number of miners (`top_x`) is met if the initial query doesn't return enough contenders.
- **Selection Criterion for Both Query Types**:

  - Miners are selected based on the least `TOTAL_REQUESTS_MADE`.
  - **Benefit**: Promotes exploration by including newer or less-assessed miners, helping them build performance history.

## Benefits

- **Improved Response Quality**: Users receive high-quality answers from top-performing miners in organic queries.
- **Exploration of New Miners**: New and less-assessed miners gain opportunities to participate, especially in synthetic queries.
- **Balanced Evaluation**: Weighted scoring ensures that performance in organic queries has a greater impact on miners' overall scores.
- **System Efficiency**: Optimized database queries enhance performance and scalability.

PD: "seasoning" :)

2024-10-18 18:58 UTC, deepbludev reviewed
## Overview

This solution enhances the selection process of miners for both organic and synthetic queries. The goal is to ensure high-quality responses for users while providing promoting exploration for new miners.

## Key Improvements

1. **Differentiated Selection Criteria**

   - **Organic Queries**: Prioritize miners with higher performance scores (`PERIOD_SCORE`) to ensure users receive top-quality responses.
   - **Synthetic Queries**: Prioritize miners with fewer total requests made (`TOTAL_REQUESTS_MADE`) to assess and evaluate less-experienced or new miners.

2. **Two-Step Contender Selection Process**

   For both organic and synthetic queries, a two-step process is implemented:

   - **Initial Query**: Select miners based on the primary criterion for the query type.
     - *Organic Queries*: Highest `PERIOD_SCORE`.
     - *Synthetic Queries*: Least `TOTAL_REQUESTS_MADE`.
   - **Secondary Query**: If the initial query doesn't yield enough miners (`top_x`), fill the remaining slots by selecting miners with the least `TOTAL_REQUESTS_MADE`. This ensures the inclusion of newer miners.

3. **Promoting New Miners**

   - By prioritizing miners with fewer total requests in the secondary query for both query types, the system ensures new miners are given opportunities to participate, allowing them to build performance history and improve their scores.

4. **Weighted Scoring Based on Query Type**

   - Assign higher weights to performance data from organic queries in scoring calculations. This emphasizes the importance of real user interactions in evaluating miner performance over synthetic assessments.

5. **Efficient Database Operations**

   - Utilize indexed columns (`PERIOD_SCORE` and `TOTAL_REQUESTS_MADE`) in queries to optimize database performance and ensure quick retrieval of contenders.

## Detailed Selection Process

### Initial Query

- **Organic Queries**

  - **Objective**: Deliver responses from the best-performing miners to users.
  - **Selection Criterion**: Miners are ranked and selected based on the highest `PERIOD_SCORE`.

- **Synthetic Queries**

  - **Objective**: Assess and evaluate miners who have had fewer opportunities.
  - **Selection Criterion**: Miners are ranked and selected based on the least `TOTAL_REQUESTS_MADE`.

### Secondary Query

- **Purpose**: Ensure the required number of miners (`top_x`) is met if the initial query doesn't return enough contenders.
- **Selection Criterion for Both Query Types**:

  - Miners are selected based on the least `TOTAL_REQUESTS_MADE`.
  - **Benefit**: Promotes exploration by including newer or less-assessed miners, helping them build performance history.

## Benefits

- **Improved Response Quality**: Users receive high-quality answers from top-performing miners in organic queries.
- **Exploration of New Miners**: New and less-assessed miners gain opportunities to participate, especially in synthetic queries.
- **Balanced Evaluation**: Weighted scoring ensures that performance in organic queries has a greater impact on miners' overall scores.
- **System Efficiency**: Optimized database queries enhance performance and scalability.


PD: "seasoning" :)

2024-10-18 19:07 UTC, deepbludev commented on validator/control_node/src/cycle/calculations.py
> +        scoring_weight = (
Here I am introducing a scoring weight

2024-10-18 19:08 UTC, deepbludev commented on validator/control_node/src/cycle/calculations.py
> +
here is the main change in this file

most of the other changes are auto-formatting

2024-10-18 19:10 UTC, deepbludev commented on validator/query_node/src/process_queries.py
> +        contenders_to_query = await get_contenders_for_task(
here is the main change in this file

passing the query type to the contender selection

the rest are auto-formatting

2024-10-18 19:10 UTC, deepbludev commented on validator/utils/database/database_constants.py
> +# CREATED_AT = "created_at"
commented out many duplicate constants to eliminate pyright alerts

2024-10-18 23:22 UTC, vincenzofanizza commented on validator/control_node/src/cycle/calculations.py
> +
out of curiosity, have you thought about how this affects previous scores? I considered adding something similar but was afraid it would not integrate well with the existing data. Maybe I'm missing something.

2024-10-18 23:35 UTC, vincenzofanizza commented on validator/db/migrations/20241018200109_contenders_score_indexes.sql
nice that you added indexes :+1:

2024-10-18 23:35 UTC, vincenzofanizza commented on validator/control_node/src/cycle/calculations.py
> +
out of curiosity, have you thought about how this affects previous scores? I considered adding something similar but was afraid it would not integrate well with the existing data. Maybe I'm missing something.

2024-10-18 23:35 UTC, vincenzofanizza commented on pyproject.toml
> +pythonVersion = "3.12"
I noticed the docker files use 3.11. It could be better to update to that version but in general, I wouldn't update the poetry file unless necessary. In my experience, it might just create compatibility issues.

2024-10-18 23:35 UTC, vincenzofanizza commented on validator/db/src/sql/contenders.py
> +    order_by = (
nice way to use a different ranking depending on the query type. Very simple but effective :+1:

2024-10-19 10:59 UTC, namoray commented on pyproject.toml
> +pythonVersion = "3.12"
Agree, we shouldn't change things irrelevant to this PR

2024-10-19 11:01 UTC, namoray requested changes
So this solution is ineffective for a few reasons:

- You're using the PERIOD_SCORE to assess which miners are best. You're using this from the contenders table. The contenders table only has information from the current cycle. Actually from the current cycle all PERIOD_SCORES are null. So this is no change to the current solution.
- Are you sure period score is a good measure of how good the responses are?
- Lots of formatting changes makes it hard to review

2024-10-19 13:38 UTC, deepbludev commented
> So this solution is ineffective for a few reasons:
> 
> * You're using the PERIOD_SCORE to assess which miners are best. You're using this from the contenders table. The contenders table only has information from the current cycle. Actually from the current cycle all PERIOD_SCORES are null. So this is no change to the current solution.
> * Are you sure period score is a good measure of how good the responses are?
> * Lots of formatting changes makes it hard to review

I just pushed a new approach that takes into account the historical scores instead.

2024-10-22 11:02 UTC, namoray commented on validator/db/src/sql/contenders.py
> +    # Get current UTC timestamp
Why is this commented?

2024-10-22 11:34 UTC, deepbludev commented on validator/db/src/sql/contenders.py
> +    # Get current UTC timestamp
it was just the AI autocomplete, I forgot to remove it

2024-10-23 11:16 UTC, closed without merging