Improve contenders ranking for organic queries
namoray/nineteen pull request #72
Opened 2024-10-18 23:01 UTC by vincenzofanizza

### Overview

Resolves: #70

The main goal of this pull request is to improve nineteen's organic selection of contenders. Here's a list of the main changes:
- Optimized ranking criterion for miners in organic queries
- Adding database indexes for efficient and scalable ranking calculations
- General linting fixes (secondary change). To avoid reviewing these, you can look at the [1st commit](https://github.com/namoray/nineteen/commit/6b3e58dcaae76c8523513fe67ff2dc1b89905a42).

### Key Changes

1. **Updated Ranking Criterion for Contenders**:
This change introduced the `__get_ranking_criterion_for_query` function in `contenders.py` to dynamically adjust the ranking of contenders based on the query type:

    - **Synthetic queries**: contenders are ordered by `TOTAL_REQUESTS_MADE` in ascending order to ensure miners are tested homogeneously.
    - **Organic queries**: contenders are ranked by a composite score consisting of three terms based on: `PERIOD_SCORE`, `TOTAL_REQUESTS_MADE`, and error rates (`REQUESTS_429` and `REQUESTS_500`).
        1. `PERIOD_SCORE`: the 1st term is a weighted sum of scores from previous cycles, ensuring that contenders that have performed well over longer periods of time are given priority.
        2. `TOTAL_REQUESTS_MADE`: the 2nd term is a weighetd sum of the miner's total number of requests. Miners with more requests are given more weight, as they are deemed more reliable.
        3. `REQUESTS_429` and `REQUESTS_500`: the 3rd term is a weighted sum of the number of 429 and 500 errors returned by the miner. Similary to the 2nd term, this ensures that more reliable miners are given more weight.

    This change ensures that contenders who are most likely to provide the highest quality inference are selected for organic queries, while still allowing synthetic queries to collect comprehensive performance data for each miner.

2. **SQL Migration for Updated Table Indexes**:
The other major change is the inclusion of two new indexes to the `contenders` table. These are added to reduce latency in the ranking calculations for organic queries.
    - `idx_contenders_synthetic` on the `TOTAL_REQUESTS_MADE` column.
    - `idx_contenders_organic` on the combination of `PERIOD_SCORE`, `TOTAL_REQUESTS_MADE`, `REQUESTS_429`, and `REQUESTS_500` columns.

    The main motivation for adding new indexes is to find the right balance between node scalability and query performance. The new index will increase the storage space of the table (potentially even more if new fields are added to the scoring criterion), but the improved read performance allows to serve queries more quickly.

### Edge Cases

- **Insufficient miner data**: If a miner does not have any previous score or has not made any requests, it will be simply penalized by the ranking system, without causing any errors. This is done thanks to the `COALESCE` function in the `ORDER BY` clause.

- **Integration with existing data**: Since the calculation of period scores was not modified, the new ranking system will seamlessly integrate with existing scores. Modifying the scoring calculation could have penalized or favored miners. For example, weighting synthetic queries less than organic queries would have penalized new miners in the short term.

### Benefits

- **Optimized miners selection**: The new ranking system ensures that the most reliable contenders are selected for organic queries, while still allowing synthetic queries to collect comprehensive performance data for each miner. This makes nineteen closer to its goal of providing a stable inference product.

- **Improved scalability**: The new index ensures that the miner selection process is more fair, while keeping nineteen's control node scalable.

### Further Improvements

- We could add other fields to the ranking, like miner capacity.
- We might change the scoring logic in the future. For this PR, the scores were considered good enough in accordance with the task description, because they already include things like time decay and bonuses.

2024-10-19 11:03 UTC, namoray requested changes
https://github.com/namoray/nineteen/pull/71

For very similar reasons to this, this is not a viable solution

2024-10-22 11:11 UTC, namoray requested changes

2024-10-22 11:11 UTC, namoray commented on validator/db/src/sql/contenders.py
> +            WITH ranked_hotkeys AS (
1. there scores for other tasks will influence how likely they are to be selected for this task
2. we rank descending by average net score. So we will always query the exact same miner first every single time, leading us to spam them right? Since their net score is static during each cycle

2024-10-22 11:11 UTC, namoray commented on validator/db/src/sql/contenders.py
> +    # Fallback to synthetic query if no contenders are found
We can't fall back to a synthetic query - do you mean  fall back to just querying by total requestS?

2024-10-22 13:25 UTC, vincenzofanizza commented on validator/db/src/sql/contenders.py
> +            WITH ranked_hotkeys AS (
1. not sure what you mean. We filter by task with the WHERE clause on line 43.
2. true. Do you think that could be mitigated by the miner's capacity? Miners can specify their capacity to the validator. If they perform well and can handle more requests I see no harm in keep forwarding them organic queries

2024-10-23 11:09 UTC, namoray commented on validator/db/src/sql/contenders.py
> +            WITH ranked_hotkeys AS (
But what's to stop us over querying that miner? What if they can only handle so many concurrent reuqests at a time?

2024-10-27 15:36 UTC, closed without merging