Improve contenders ranking for organic queries
namoray/nineteen pull request #73
Opened 2024-10-19 14:37 UTC by vladojov

Resolves

# Overview

This PR tries to improve contenders ranking for organic queries by prioritising contenders who have historically done good. As an assessment of contender's "goodness", the scoring stats from the last cycle are used, which are kept in the local DB.

The solution goes as follows:

First we increase the number of initially selected contenders for a task. (Currently, this number is twice as the previous value, i.e., `top_x` in `get_contenders_for_task()` is increased from 5 to 10. This can be further adapted). Then, we get the latest scoring stats for the initially selected contenders from the DB. Next, we calculate a weighted average of the `NORMALISED_NET_SCORE` from the scoring stats and the contender's `TOTAL_REQUESTS_MADE` as a current score. Finally, we use this value to further filter the initially selected contenders for the task, by selecting those contenders with highest weighted average.

# Goals

The goals of this improvement are threefold:

1) Rank contenders better when distributing organic queries, as it is more likely that a miner that has performed good in the past will perform good in the future.

2) Give further incentive for miners to have good performance for longer period of time in order to increase their chances of being selected.

3) Participate in the "dev seasoning" challenge :)

In addition, prioritising contenders based on their historical scores has been seen as an important dev todo (see `todos.md`).

# Edge cases

It is possible for a contender not to have scoring stats from the last cycle. In this case, the scoring stats score (`NORMALISED_NET_SCORE`) is explicitly set to 0 so that only the current score (`TOTAL_REQUESTS_MADE`) is taken into account when calculating their weighted average.

# Future improvements

Ideas for future improvements:

* Use scoring stats from more than one cycle, by weighting them in a way that stats from more recent cycles have greater weight.

* Include several scores into the combining equation

2024-10-20 09:17 UTC, namoray commented on validator/query_node/src/process_queries.py
> +            contenders_to_query = await _prioritise_contenders_by_scoring_stats(connection, task, contenders_for_task)
Why double the amount of candidates now?

2024-10-20 09:19 UTC, namoray commented on validator/query_node/src/process_queries.py
> +        combined_score = await _combine_current_score_with_scoring_stats(
I think the name 'current score' is a bit misleading here, what does that mean?

2024-10-20 09:21 UTC, namoray reviewed
This is a very well thought through, simple solution. 

One minor point: i find the naming conventions confusing and not precise enough (current_score, scoring_stats_score, weight_stats etc). No biggie / fixable
One slighty bigger point: There is a non trivial amount of processing happening here. DO you think that is really feasible on every query?

2024-10-20 09:22 UTC, namoray commented on validator/query_node/src/process_queries.py
> +    return (current_score * weight_current + scoring_stats_score * weight_stats) / (weight_current + weight_stats)
So we are happy to have some probability to send a request from the frontend to a contender with 0 'scoring_stats_score'? Really? We've determined them to be terrible, and yet still want to serve real user requests?

2024-10-20 14:42 UTC, vladojov commented
> This is a very well thought through, simple solution.
> 
> One minor point: i find the naming conventions confusing and not precise enough (current_score, scoring_stats_score, weight_stats etc). No biggie / fixable One slighty bigger point: There is a non trivial amount of processing happening here. DO you think that is really feasible on every query?

Thank you for the feedback. Yes, I've tried to be simple as possible, considering the time-frame of the challenge and me being unfamiliar with the code base. The description of the task was excellent and the given hits were very helpful.

I agree naming can be improved. I guess for good naming you need to spend some time with the project and the code base. The particular function where most of the confusing naming occurs can even be refactored into a more general one, for computing weighted average of given values and weights.

Regarding the additional amount of processing, probably some further investigation and performance testing is needed. The most expensive operation is the additional query for finding the latest scoring stats, which I believe is not overly complex. This is due to: i) it is executed for a fixed set of contenders and ii) the `CONTENDERS_WEIGHTS_STATS_TABLE` should not have too many rows as there are functions for deleting old rows. Also, appropriate indexes should help here for faster execution.

If this approach proves to be overwhelming, there are other ways of implementing the main idea, which might have better performance. For example, we might create another table for keeping only the latest scoring stats or extend the contenders table with a field for keeping the last cycle score. These approaches might even be incorporated into the query in `get_contenders_for_task()` somehow. Nevertheless, these would require additional updates on each cycle, after the stats scores are computed.

2024-10-22 10:46 UTC, namoray commented
Accepting this one as a solution 👍

2024-10-22 11:01 UTC, namoray commented on validator/query_node/src/process_queries.py
> +        contenders_for_task = await get_contenders_for_task(connection, task, top_x=CONTENDERS_PER_TASK * 2)
We still only select 10 contenders to rank and compare right? 

If these 10 are all really bad, then we're going to pick the best of a bad bunch

2024-10-22 11:02 UTC, namoray requested changes
Actually on further review this solution is not suitable because we're only re-reranking the initial miners chose.

What if the initial miners chose are all ready bad? we're not prioritisng good miners for the frontend here

2024-10-22 15:51 UTC, vladojov commented
Hi @namoray Here was my reasoning:

We know the current least bad miners (`get_contenders_for_task()`) and we have the historical scores in `CONTENDERS_WEIGHTS_STATS_TABLE`, so we can get the last cycle best miners.

Do we want to combine them?

If not, we can just return the last cycle best miners, but we risk that some of them started behaving bad, i.e., set limits, etc.

Maybe it's better to combine them. Then, how to combine them?

We need to operate over more miners than the desired number we want to return (in our case 5), in order to be able to have choice. I've chosen 10, but these numbers can be configured and tuned.

Possible scenarios:

1. Select last cycle best from the least bad miners. This means: find 10 least  bad miners, order them by last cycle 'goodness' and return most good 5.

2. Select least bad from the last cycle best. This means: find 10 last cycle best miners, order them by 'badness' and return the least bad 5.

3. Select combined least bad and last cycle best miners according to a weighted average. Choose appropriate weights on 'goodness' and 'least badness' scores. We can tune the weights so that we give advantage to last cycle best or the currently least bad miners. Return 5 with best combined score.

I've tried to implement Scenario 3. Get the least bad miners, get their last cycle 'goodness' score, compute weighted average from their 'badness' and 'goodness' scores, and select the best 5. According to the weights currently chosen, we give advantage to least bad miners.

Is my reasoning right? What scenario is best?

I'm happy to discuss the scenarios and implement the most appropriate one.

2024-10-22 22:25 UTC, vladojov commented
Hi @namoray The last commit implements even a more simple solution, which goes as follows:

If we have an organic query, select contenders suitable for a task by prioritising those who performed good in the last cycle, based on the normalised net score metric. In case there are not enough contenders, fill the rest (up to `top_x`) by selecting contenders as we do for synthetic queries. Selecting contenders for synthetic queries stays same as before.

2024-10-23 11:08 UTC, namoray commented
Looking at the latest commit @vladojov , Wont we just be sending 100% of the queries to the best performing miner? They will get overwhelmed very quickly right because their servers are now getting all the traffic

2024-10-27 15:36 UTC, closed without merging